import { getImageUrl } from './utils/utils.js';

export default function Profile({ person, size, isSepia, thickBorder }) {
  return (
    <section>
      <img src="https://i.imgur.com/MK3eW3As.jpg" alt="Katherine Johnson"></img>
      <Bio />
      <h1>Amazing scientists</h1>
      <Generated />
      <TodoList />
      <br />
      <b>A picture using curly braces: A window inth the JavaScript world</b>
      <br></br>
      <br></br>
      <Avatar />
      <br></br>
      <br></br>
      <br></br>
      {/*Pass props to the child component Avatar */}
      <SecondAvatar
        person={{
          name: "Lin Lanying",
          imageId: '1bX5QH6'
        }}
        size={100}
      />
      {/*Nesting JSX tag using your own components will pass the componenet inside as a child */}
      <Card>
        <SecondAvatar
          size={100}
          person={{
            name: 'Katsuko Saruhashi',
            imageId: 'YfeOqp2'
          }}
        />
      </Card>


      <SecondAvatar size={80}
        person={{
          name: 'Aklilu Lemma',
          imageId: 'OKS67lh'
        }}
      />

      {/* <div className="card">
       <SecondAvatar {...props}
       />
     </div> */}

      <div>
        {/* {Mike('black', formatDate(today))}
         */}
         <Mike />
      </div>

    </section>
  )
}


function Mike({ color = 'black', time = formatTime(today) }) {
  return (
    <h1 style={{ color: color }}>
      {time}
    </h1>
  );
}


function Card({ children }) {
  return (
    <div className="card">
      {children}
    </div>
  );
}



export function Generated() {
  return (
    <section>
      <h1>This was generated by an AI</h1>
      <img src='https://equitrekking.com/images/uploads/ethiopian%20car.jpg' />

    </section>
  );

}

//But as the Web became more interactive, logic increasingly determined content. 
//JavaScript was in charge of the HTML! This is why in React, rendering logic and markup live together in the same place—components.

const today = new Date();

function formatTime(date) {
  return new Intl.DateTimeFormat('en-US', {
      hour: '2-digit', 
      minute: '2-digit', 
      second: '2-digit',
      hour12: true // Use 24-hour format; set to true for 12-hour format
  }).format(date);
}

function formatDate(date) {

  return new Intl.DateTimeFormat(
    'en-US',
    { weekday: 'long' }
  ).format(date);

}

const person = {
  name: 'Gregorio Y. Zara',

  imageInfo: {
    baseUrl: 'https://i.imgur.com/',
    imageId: 'yXOvdOS',
    imageSize: 's',
    fileExtension: '.jpg',
    alt: "Hedy Lamarr",
    className: "photo"
  },

  theme: {
    backgroundColor: 'black',
    border: ' 2px solid black',
    borderRadius: '10px',
    color: 'white'
  }
};


export function TodoList() {

  return (
    // This empty tag is called a Fragment. Fragments let you group things without leaving any trace in the browser HTML tree.
    <div style={person.theme}>
      <h1>Hedy Lamarr's TODO for {formatDate(today)} </h1>
      <img
        src={person.imageInfo.baseUrl + person.imageInfo.imageId + person.imageInfo.imageSize + person.imageInfo.fileExtension}
        alt={person.imageInfo.alt}
        className={person.imageInfo.className}
      ></img>

      {/*  To pass a JS object in JSX, you must wrap the object in another pair of curly braces: person={{ name: "Hedy Lamarr", inventions: 5 }}.

      <ul style={{
      backgroundColor: 'black',
      color: 'pink'
      }}> 
      
      */}
      <ul>
        <li>Invent new traffic lights(She did not Invent traffic lights)</li>
        <li>Rehearse a movie scene</li>
        <li>Imporve the spectrum technology</li>
      </ul>
    </div>
  )
}

export function Bio() {
  return (
    <div>
      <div className="intro">
        <h1>Welcome to my website!</h1>
      </div>
      <p className="summary">
        You can find my thoughts here.
        <br /><br /><br />
        <b>And <i>pictures</i></b> of scientists!
      </p>
      <br />
    </div>
  );
}


function Avatar() {
  const avatar = 'https://i.imgur.com/7vQD0fPs.jpg';
  const description = 'Gregorio Y. Zara';
  return (
    <img
      className="avatar"
      src={avatar}
      alt={description}
    />
  )
}


//You can write it by calling out the whole props object
/*function SecondAvatar(props) {
  const avatar = 'https://i.imgur.com/7vQD0fPs.jpg';
  const description = 'Gregorio Y. Zara';
  return (
    <img
      className="avatar"
      src={getImageUrl(props.person)}
      alt={props.name}
      width={props.size}
      height={props.size}
    />
  )
}*/

//OR destructure it into individual props
function SecondAvatar({ person, size = 100 }) {
  const avatar = 'https://i.imgur.com/7vQD0fPs.jpg';
  const description = 'Gregorio Y. Zara';
  return (
    <img
      className="avatar"
      src={getImageUrl(person)}
      alt={person.name}
      width={size}
      height={size}
    />
  )
}

function ThirdAvatar(props) {
  let person = props.person;
  let size = props.size;

}


/* <section> is lowercase, so React knows we refer to an HTML tag.
<Profile /> starts with a capital P, so React knows that we want to use our component called Profile. */

// export default function Gallery() {
//   return (
//     <section>
//       <Bio />
//       <h1>Amazing scientists</h1>
//       <Profile />
//       <Generated />
//       <TodoList />
//       <br />
//       <b>A picture using curly braces: A window inth the JavaScript world</b>
//       <br></br>
//       <br></br>
//       <Avatar />
//       <br></br>
//       <br></br>
//       <br></br>
//       {/*Pass props to the child component Avatar */}
//       <SecondAvatar
//         person={{
//           name: "Lin Lanying",
//           imageId: '1bX5QH6'
//         }}
//         size={100}
//       />

//       <SecondAvatar
//         size={100}
//         person={{
//           name: 'Katsuko Saruhashi',
//           imageId: 'YfeOqp2'
//         }}
//       />

//       <SecondAvatar size={80}
//         person={{
//           name: 'Aklilu Lemma',
//           imageId: 'OKS67lh'
//         }}
//       />
//     </section>
//   );
// }